# Generated by Django 4.2.20 on 2025-04-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_dislikes_post_image_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
